blank_issues_enabled: false # 禁止创建空白 Issue，强制用户使用预设模板
contact_links:
  - name: 安全联系人
    about: 请向 security@tiangolo.com 报告安全漏洞 # 安全问题反馈联系方式
  - name: 提问或遇到问题 # 提问或遇到问题
    about: 在 GitHub Discussions 中提问或咨询问题。 # 引导用户去 Discussions 版块提问
    url: hhttps://github.com/csaay/fastapiTpl/discussions/categories/questions
  - name: 功能请求 # 功能请求
    about: 建议想法或请求功能，请先从提问开始，说明你想要实现什么。可能已经有某种方法可以做到了。 # 建议先在 Discussions 中讨论想法
    url: https://github.com/csaay/fastapiTpl/discussions/categories/questions
