name: Lint Backend # 后端代码检查

on:
  push:
    branches:
      - main # 推送到 main 分支时触发
  pull_request:
    types:
      - opened # PR 创建时触发
      - synchronize # PR 更新时触发

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 检出代码
        uses: actions/checkout@v6
      - name: Set up Python # 设置 Python 环境
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install uv # 安装 uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.4.15"
          enable-cache: true
      - run: uv run bash scripts/lint.sh # 运行 Lint 检查脚本
        working-directory: backend
